### ISSUE TITLE
Fix libelf linkage

### ISSUE THREAD

**Issue by prologic** [netdata/kernel-collector#16]
```sh
/kernel-collector # find . -type f -name '*.so'
./library/libbpf.so
./user/libnetdata_ebpf.so
/kernel-collector # ldd ./library/libbpf.so
	/lib/ld-musl-x86_64.so.1 (0x7f20d764c000)
Error loading shared library libelf.so.0: No such file or directory (needed by ./library/libbpf.so)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f20d764c000)
```

**Comment by thiagoftsm** [comment]
I am assigning myself here for the same motive explained in the previous.

**Comment by thiagoftsm** [comment]
I finished the tests with libelf now and I decided to link it statically, because it only adds 35kb to our shared library and libbpf shared library, so the final package will raise only 70kb, a size that I consider acceptable. @Ferroin and @prologic do you have objections to add 70kb to the final package?

**Comment by prologic** [comment]
No I absolutely do not! ~70kB is nothing and `libelf.so.X` is actually a painful dependency to get right anyway. `musl` / `libc` is much easier to deal with :)

**Comment by thiagoftsm** [comment]
> No I absolutely do not! ~70kB is nothing and `libelf.so.X` is actually a painful dependency to get right anyway. `musl` / `libc` is much easier to deal with :)

Thank you! :D 
When I finish to compile the kernel 5.5 and do the necessary tests, I will create a PR with the necessary changes.

**Comment by prologic** [comment]
Is the libbpf / kernel 5.5 two separate things? i.e: two separate PRs?

Also when you put up the PR for Kernel 5.5 can you also add it to the build matrix in `.github/workflows/build.yml`? :)

**Comment by prologic** [comment]
Unassigning me here as its all you @thiagoftsm :) And removing "bug" and adding "enhancement" as that's what this has become :)

**Comment by thiagoftsm** [comment]
> Is the libbpf / kernel 5.5 two separate things? i.e: two separate PRs?
> 
> Also when you put up the PR for Kernel 5.5 can you also add it to the build matrix in `.github/workflows/build.yml`? :)

I am expecting that kernel 5.5 can run with 5.4 eBPF code, unless they did big changes, something that I am not expecting. They will be different PRs only case we have a big change.
I had to wait, because the unique VM that has more than the current kernel, was exactly the VM that I was compiling the kernel.
